Add command to sign a withdrawal credentials update message using a validator keystore
eth-educators/ethstaker-deposit-cli pull request #88
Opened 2024-08-16 12:33 UTC by valefar-on-discord

There is a cohort of users who have lost or are missing their mnemonic and are unable to update their withdrawal credentials. As of now, these funds are locked permanently and indefinitely. We have a potential solution that can allow these users to regain their funds though we have no approval or proper implementation. One of the necessary components of this solution is a signature from the validator keystore that can be used as a proof of ownership of the validator.  This adds the ability for a user to generate said signature.

The users runs `generate-bls-to-execution-change-keystore` with the provided keystore, password, validator index, and designed execution address to update their withdrawal credentials with.  This command outputs and signature json file where the message will contain the provided execution address and validator index.

2024-08-18 20:44 UTC, valefar-on-discord commented
I'm thinking about changing the logic to be a more generic "sign message with validator keystore"...

2024-08-22 00:55 UTC, valefar-on-discord commented on ethstaker_deposit/utils/constants.py
> +DOMAIN_BLS_TO_EXECUTION_CHANGE_KEYSTORE = bytes.fromhex('0B000000')
This needs to be changed: https://github.com/prysmaticlabs/prysm/blob/7c213ce161cb929659c9cd96c7bfa08bcd8ef820/config/params/mainnet_config.go#L174C2-L174C21

2024-08-27 14:34 UTC, remyroy commented
It would be nice if you could link the related proposals if they exist in a draft or a working document somewhere else.

2024-08-27 23:44 UTC, valefar-on-discord commented
> It would be nice if you could link the related proposals if they exist in a draft or a working document somewhere else.

The only location for the proposal right now is https://github.com/eth-educators/update-credentials-without-mnemonic

If we are in agreement, my plan would be to get this landed (when ready) and create a new release. I'll then update the other repo with the new instructions and then we can broadcast to determine interest.

2024-08-29 00:57 UTC, yorickdowne commented
Do you want the logic as-is in here, or do you prefer the more generic "sign message" logic?

2024-08-29 01:07 UTC, valefar-on-discord commented
After some thought I'd prefer to keep it as is.

The generic signing came as an idea with the Stakers Union project where you have to turn off your validator to prove ownership. My thought was signing the Stakers Union's Oath with the validator keystore would do just as well.

But I am also of the opinion that any form of generic signing is dangerous. This needs to be a highly secure project based on the operations. I would rather build out a separate command for that use case if the need arises.

2024-08-29 05:50 UTC, yorickdowne commented
OK, I agree. I am interested in seeing this in. Even if we end up backing it out again, if there’s just not appetite to actually do this, from the Ethereum devs.

Let’s see what Remy says when he’s back next week.

2024-09-03 14:56 UTC, remyroy commented
I wish there was more efforts into bringing this as an official EIP and gathering comments and reviews from peers in the ecosystem. I'm happy to review this PR and include it in the project but I fear it will not be used if the principles and the specs behind this feature isn't accepted at the protocol level.

2024-09-03 16:31 UTC, yorickdowne commented
We’d include this to gauge interest and see how many people are impacted. That’s how we get the protocol on board. Chicken and egg.

At some point it’ll be removed again.

2024-09-04 18:03 UTC, remyroy requested changes
One small change I would make to the documentation and everything else seems good.

2024-09-07 02:54 UTC, valefar-on-discord commented on docs/src/generate_bls_to_execution_change_keystore.md
> +This command is associated with the a proposed solution to update withdrawal credentials for those who are missing their mnemonic. At this point this has not been approved or implemented and there is
Added a reference

2024-09-09 12:59 UTC, merged